name: Linux Cloud PC - RDP Funcional

on:
  workflow_dispatch:

jobs:
  build:
    name: Subindo Linux com RDP...
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Instalar Interface e RDP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          echo xfce4-session > ~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "runner:123456" | sudo chpasswd

      - name: Iniciar Tunel Automatico
        uses: mxschmitt/action-tmate@v3
        
